### ISSUE TITLE
How to add SMS to your civic hack with Twilio

### ISSUE THREAD

**Issue by GregBaugues** [chihacknight/join-a-breakout#10]
**About the Group**
A lot of civic hacks use SMS for notifications, to collect data from folks who don't have a smart phone, and to make their app mobile without designing a native app. If this is interesting to you, swing by and we'll figure out how to make it work for you app and add some credits to your Twilio account to play with. 

**Group Leader**
Greg Baugues serves as a developer evangelist at Twilio and lives in Chicago.

**Comment by derekeder** [comment]
Closing until Twilio is sponsoring again and @GregBaugues is back.
