### ISSUE TITLE
Bicycle Breakout

### ISSUE THREAD

**Issue by zscore** [chihacknight/join-a-breakout#2]
**About the group:** 
We are trying to make Chicago a better safe for cyclists! Projects include mapping pavement quality via [phone accelerometers]( http://project-pavement.herokuapp.com/) and setting up custom OSRM routing profiles for the [bicycle trip planner map](http://pbikerouting.herokuapp.com/).

**Who we're looking for:**
Web developers, data scientists, and people passionate about the cycling community and bicycling in Chicago!

**Tools:**
Ruby on Rails for the web app, the Scipy Stack for data analysis, Leaflet for visualization (map), OSRM for routing, Swift for iOS, Java for the Android app

**Where we meet:**
the cafeteria

**Comment by stevevance** [comment]
I made some changes to the formatting, and some of the text.
