### ISSUE TITLE
Redistricting with Transparency

### ISSUE THREAD

**Issue by Ken-Dallmeyer** [chihacknight/join-a-breakout#22]
Ken Dallmeyer:

I have decided to suspend activity on Redistricting with Transparency for the time being.  I will be working with the Map It group to create usable base maps of demographics.

Whether to have Independent Map Amendment referendum question on the November election ballot is now before the Illinois Supreme Court and the focus of interest groups is on getting court approval.  How to implement a mapping process has been sidelined. 

When the time seems more ripe, I will reopen the task.  

If there is anyone interested in taking on the lead for the Redistricting with Transparency  working group I will be happy to share my thoughts and research, some of which is below.

Ken

The Short Term Agenda at https://drive.google.com/open?id=1bxZ4iy57a3_YQqMbnERVIQb0tfa57R0JuSC5f-9jG50

New channel created within Slack Chi Hack Night - Redistricting_il

See the proposed work program  and work to date on this Google Drive.
https://drive.google.com/folderview?id=0B7VmSjRJOuOaZGNGS2RVSktGVXM&usp=sharing

[Redistricting with Transparency.pdf](https://github.com/chihacknight/join-a-breakout/files/338259/Redistricting.with.Transparency.pdf)

Need interested people from many backgrounds. Meet in Cafeteria.
Ken
Kenneth E. Dallmeyer
Kenneth.E.Dallmeyer@gmail.com
(847) 376-9758

**Comment by Ken-Dallmeyer** [comment]
Derek,

So how do I get it restored?

**Comment by derekeder** [comment]
Hi Ken - we can reopen this issue. I'll do it now.

**Comment by Ken-Dallmeyer** [comment]
Derek,

I have decided to suspend activity in the Redistricting with Transparency working group.  See the note in working group #22

Ken

**Comment by derekeder** [comment]
Thanks for the note Ken. We can close it for now.
