### ISSUE TITLE
Lets go meta: custom wrapper for join-a-breakout...breakout group

### ISSUE THREAD

**Issue by easherma** [chihacknight/join-a-breakout#33]
### About the group
We've been experimenting with using Github Issues as a way to track the ongoing working and educational groups that meet here at hack night. 

This is a great example of the 'hacking' part of hack night; using an existing tool for a new/originally unintended purpose. 

So far, the group has done a great job adapting to this change. **Lets take this hack to a new level!**

We suspect that using Github issues is not a 100% perfect solution for our problem as-is. 

For example, in order to create a new breakout group, you have to create a Github account. If you're a non-techie/not on Github already, this is _L A M E_ and is one more obstacle for new people to create new groups. 

But there are other aspects as well that could be tweaked. 
### Group leaders
Eric Sherman
ericandrewsherman@gmail.com

### Who we're looking for
We are looking to collect user feedback from people, _especially if you've never used Github_! We want to scope out what a custom wrapper around Github Issues would look like that also integrates with the platform and style of chihacknight.org
Also looking for:

- UI Dev
- Github API experts
- Javascript, Python, whatever (people who can write code)

### Tools
- Github API
- Jekyl/Github Pages

### Relevant Links
https://chihacknight.org/breakouts.html

### Where we meet
Hopefully we'll grab a side room or find a corner to chill in.

**Comment by easherma** [comment]
Potentially useful/relevant stuff:

http://prose.io/#about
https://github.com/michael/github

**Comment by easherma** [comment]
Feature tweaks:

* Custom issue order
* Guest Account
* Putting breakout groups to 'sleep' (potentially automatically)
* Integration with slack bot

**Comment by easherma** [comment]
[made a repo](https://github.com/chihacknight/github-issue-wrapper)

**Comment by easherma** [comment]
Ryan:
starting a bootcamp, some light coding, no github 
exta github stuff at the top for the breakout group repo that has nothing to do with the project

**Comment by derekeder** [comment]
Not meeting tonight, closing.
