### ISSUE TITLE
Scaling Demand-Driven Open Data (DDOD)

### ISSUE THREAD

**Issue by dportnoy** [chihacknight/join-a-breakout#35]
### About the group
See [218th Chi Hack Night: Demand-Driven Open Data (DDOD)](https://chihacknight.org/events/2016/08/16/demand-driven-open-data.html)

Problem: 
- How can we contribute to maximizing the public good and economic value of open data?
- How can we scale the DDOD beyond HHS?
- How can we mitigate risk to open data between presidential administrations?

### Group leaders
David Portnoy, former EIR at HHS

### Who we're looking for
Those with experience working with open data.
Interested in refining the product roadmap for DDODx.
Can describe the problems they’ve encountered.
Understanding of data management, including MDM, federation, versioning.

### Tools
_______

### Relevant Links
ddod.healthdata.gov

### Where we meet
______

**Comment by dportnoy** [comment]
**Thank you to all Chi Hack Night attendees who provided their input.  It’s really appreciated!**

Stay tuned for more.  In the meantime, for those who asked for additional links...

* ChiHackNight: https://chihacknight.org/events/2016/08/16/demand-driven-open-data.html
* Video: https://youtu.be/v9PHWBLQFRE
* Intro to DDOD for Data Owners: http://www.slideshare.net/DavidPortnoy/intro-to-ddod-for-data-owners
* HHS project website: http://ddod.healthdata.gov
* DDOD project description: http://www.hhs.gov/idealab/projects-item/demand-driven-open-data/
* White House Open Data Roundtable: http://www.slideshare.net/DavidPortnoy/impact-of-ddod-on-data-quality-white-house-2016
* White House Open Data Innovation Summit: https://www.data.gov/event/white-house-open-data-innovation-summit/
* MIT Chief Data Officer Conference: http://www.mitcdoiq.org/event/2016-agenda/

**Comment by derekeder** [comment]
Closing for now since it's been a few weeks

**Comment by dportnoy** [comment]
Looking for hacktivists passionate about open data, analytics and dataviz!  We need to do massive analytics and visualization on the federal government's metadata.  Lot's of gems to discover.  This work will become part of the public body of knowledge for metrics on data quality, discoverability and usability.
