### ISSUE TITLE
De-dupin' Campaign Finance Data

### ISSUE THREAD

**Issue by derekeder** [chihacknight/join-a-breakout#5]
**About the group** Want to help clean up Illinois campaign finance data and listen to podcasts about politics? Using the [Dedupe.io](http://dedupe.io/) web interface, we will be reviewing and matching political donation records that are similar so we can find out how much each donor is giving. When we're done, the data will be released publicly for all to use.

**Group leaders** Derek Eder, [derek@derekeder.com](mailto:derek@derekeder.com)

**Who we're looking for** Anyone who is interested in Illinois politics. No coding required! Wanna help out remotely, just [email Derek](mailto:derek@derekeder.com)!

**Tools** We'll be using a tool built by DataMade called [Dedupe.io](http://dedupe.io/). All you'll need is a laptop!

**Where we meet** Either in the back couches in the cafeteria or one of the free rooms

**Comment by bencooper222** [comment]
One of my favorite podcasts: http://fivethirtyeight.com/tag/elections-podcast/ 
Really wonkish and from Nate Silver, antipundit in chief. Enjoy!
