### ISSUE TITLE
Civic Tech 101

### ISSUE THREAD

**Issue by GovInTrenches** [chihacknight/join-a-breakout#9]
This is a short 15 minute orientation to civic technology. We go over the concepts of open data, open source, and the importance of community organizing in our work. We'll go over what resources and available at hack night and some examples of our work. 

We meet in 111 N Canal (the room with the big door).

**Comment by KrzysztofMadejski** [comment]
@GovInTrenches could you share the presentation for it? We're building code of conduct / focusing on values in Code for Poland.

**Comment by csethna** [comment]
Great chat! Thanks for such an engaging and informative session. Toes are wet, looking forward to jumping in!

**Comment by KrzysztofMadejski** [comment]
Thanks @GovInTrenches for the presentation (via Slack)!

https://www.youtube.com/watch?v=H_on0kXZ07M&feature=youtu.be
